version: '2'
services:
    hochzeitclick11-app:
        image: hochzeitclick11
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hochzeitclick11-mysql:3306/hochzeitclick11?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hochzeitclick11-elasticsearch:9300
        ports:
            - 8080:8080
    hochzeitclick11-mysql:
        extends:
            file: mysql.yml
            service: hochzeitclick11-mysql
    hochzeitclick11-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hochzeitclick11-elasticsearch
